name: Build
on:
  push:
  workflow_dispatch:

env:
  SHOULD_DEPLOY: ${{ (!contains(github.event.head_commit.message , '[skip ci]') && github.repository == 'mc-wiki/mcw-calc' && github.ref == 'refs/heads/main') || github.event == 'workflow_dispatch' }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: https://tools.minecraft.wiki/static/
          environment: production

      # - name: Deploy to MW
      #   if: ${{ env.SHOULD_DEPLOY == 'true' }}
      #   run: pnpm run deploy
      #   env:
      #     ACCESS_TOKEN_PROD: ${{ secrets.ACCESS_TOKEN_PROD }}
      #     # ACCESS_TOKEN_DEV: ${{ secrets.ACCESS_TOKEN_DEV }}

      - name: Upload file to tools
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.TOOLS_SSH_IP }}
          username: ${{ secrets.TOOLS_SSH_USER }}
          key: ${{ secrets.TOOLS_SSH_PRIVATE_KEY }}
          source: dist/
          target: /var/www/html/static/
