name: Deploy
concurrency: deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message , '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Deploy
        run: pnpm run deploy
        env:
          USERNAME_PROD: ${{ secrets.USERNAME }}
          PASSWORD_PROD: ${{ secrets.PASSWORD }}
          USERNAME_DEV: ${{ secrets.USERNAME_DEV }}
          PASSWORD_DEV: ${{ secrets.PASSWORD_DEV }}
